version: 0
verbose: true
run:
  mounts: # mount configurations Available keys: NOW, UUID,
    - !mounts.SSHCode &code_mount
      local_path: .
      # host_path: $JYNMNT/latent-planning/latent-planning
      local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes-demo.tar
      host_path: "{secret.JYNS_SLURM_DIR}/jaynes-demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes_demo"
      remote_tar: "{secret.JYNS_SLURM_DIR}/jaynes-demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes_demo.tar"
      pypath: true
      excludes: >-
        --exclude='data' --exclude='assets/third_party' --exclude='assets/development/objaverse' 
        --exclude='assets/development/orbit-legacy-assets' --exclude='assets/development/robots' --exclude='assets/development/rooms'
        --exclude='samples' --exclude='images' --exclude='videos'
        --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
        --exclude='*__pycache__' --exclude='*.git' --exclude='*.gif'
        --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
        --exclude='*.log*' --exclude='*.hdf5'
      compress: true
  runner: !runners.Slurm &slurm
    envs: >-
      LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US
    setup: |
      source "{secret.JYNS_SLURM_DIR}.jaynes_bash"
      conda activate torch311
      sleep 0.1;
      #export MUJOCO_GL=egl
      echo $PWD
    startup: >-
      pip install jaynes ml-logger -q;
    pypath: "{mounts[0].host_path}"
    work_dir: "{mounts[0].host_path}"
    # partition: normal # not clear what the partition is like
    time_limit: "1:0:0"
    n_cpu: 2
    n_gpu: 2
    mem: 24G
    interactive: true
    # post_script: >-
    #   make --directory $HOME cleanup;
  launch: !ENV
    type: ssh
    ip: "{secret.JYNS_SLURM_HOST}"
    username: "{secret.JYNS_USERNAME}"
    password: "{secret.JYNS_SLURM_PASSWORD}"

